import { PropsWithChildren } from 'react';
import Head from 'next/head';

interface Props extends PropsWithChildren {}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>My Tennis Coach 🎾</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="skip">{children}</main>
    </>
  );
}
